tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "mac-cleanup/mac-cleanup-py"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Fast, highly customisable system info script
brew "neofetch"
# Platform built on V8 to build network applications
brew "node@16"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Python cleanup script for macOS
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
