tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mac-cleanup/mac-cleanup-py"
# Pack, ship and run any application as a lightweight container
brew "docker"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Fast, highly customisable system info script
brew "neofetch"
# Platform built on V8 to build network applications
brew "node"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Python cleanup script for macOS
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
# UI toolkit for building applications for mobile, web and desktop
cask "flutter"
